### ISSUE TITLE
Configuración inicial de proyecto Front-End

### ISSUE THREAD

**Issue by carlosmding** [carlosmding/Joyeria_Front_End#1]

**Comment by Neltrin22** [comment]
Se realiza la configuración del Fron-End en Angular para el proyecto de la joyería, el cual debe tener la capacidad de interacción con el usuario para la gestión de los productos, se utiliza el IDE Visual Studio Code

![Image](https://user-images.githubusercontent.com/106124779/234160682-df5b8843-63b7-4786-a875-a69c751f1db7.jpg)
